// <auto-generated />
namespace BasakWeb.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initiale334 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initiale334));
        
        string IMigrationMetadata.Id
        {
            get { return "201904281331447_initiale334"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
