// <auto-generated />
namespace BasakWeb.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Initiale33413 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initiale33413));
        
        string IMigrationMetadata.Id
        {
            get { return "201904291954348_Initiale33413"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
